[project]
name = "cafe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch==2.5.1"
]

[tool.uv]
index-url = "https://download.pytorch.org/whl/cu121"